# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-08 15:45
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapsUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caps_name', models.CharField(max_length=150)),
                ('files', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/alex/django1/userena/caps'), upload_to='')),
                ('description', models.TextField(max_length=400)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'caps',
            },
        ),
    ]
