# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-08 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_capsupload'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='capsupload',
            table='account_caps',
        ),
    ]
