# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160808_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsupload',
            name='files',
            field=models.FileField(storage='/home/alex/django1/userena/caps', upload_to=''),
        ),
        migrations.AlterModelTable(
            name='capsupload',
            table=None,
        ),
    ]
