# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 09:02
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160809_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsupload',
            name='files',
            field=models.FileField(storage='/home/alex/django1/userena/caps', upload_to=accounts.models.user_directory_path),
        ),
    ]
